apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: acrforaksdemo.azurecr.io/sandeepanumula92/webapplication1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
          name: dotnetapp-port
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: webapp
spec:
  ports:
  - port: 80
    targetPort: dotnetapp-port
  selector:
    app: webapp
  type: LoadBalancer
